transform       = {body}
body            = [comment] ("</" | "<" tag body | literal body);
comment         = "<!---" {?-"--->"} "--->";
literal         = ("<" | {?-"#"-"<"} "<" | {"#" expression "#"} "<" ) | ({?-"<"} "<")
tag             = name-space identifier spaces attributes ("/>" | ">" [body "</" identifier spaces ">"]);
name-space      = < tagLib[].getNameSpaceAndSeperator() >;
attributes      = ({spaces attribute} "/>" | {spaces attribute} ">") | attribute-value;
attribute       = attribute-name  spaces "=" spaces attribute-value;
attribute-name  = ("expression"|'expression'|expression) | identifier;
attribute-value = expression;
identifier      = (letter | "_") {letter | "_"|digit};
letter          = "a".."z"|"A".."Z";
digit           = "0".."9";
expression      = <ExprTransfomer.expression()>; (* Ruft den Expression Transformer auf. *)
spaces          = {space};
space           = "\s"|"\t"|"\f"|"\t"|"\n";

{"x"}= 0..n
["x"]= 0..1
